### ISSUE TITLE
What did I do wrong

### ISSUE THREAD

**Issue by gitweb1** [githubteacher/intermediate-may#14]
git push origin add-fuquay-page 
Username for 'https://github.com': 
Password for 'https://gitweb1@github.com': 
To https://github.com/githubteacher/intermediate-may.git
 ! [rejected]        add-fuquay-page -> add-fuquay-page (fetch first)
error: failed to push some refs to 'https://github.com/githubteacher/intermediate-may.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by githubteacher** [comment]
You tried to push to the same branch I am pushing to. Did you create a different branch for your work or were you using the add-fuquay-page branch?

**Comment by gitweb1** [comment]
Thanks. I just created a new branch with a different name and it worked.
