### ISSUE TITLE
What's the proper way to undo my pull request.

### ISSUE THREAD

**Issue by DanielSiefert** [githubteacher/intermediate-may#16]
I accidentally hit the merge button, is clicking the revert the way to go? or would it be easier to just edit my file a bit commit again and create a new pull request?

**Comment by githubstudent** [comment]
@OfCourseITestedIt Definitely click the revert button. It creates a new branch and opens a new PR that reverts all the changes the original PR introduced. Doing it this way makes public the record of why that PR had to be reverted, which is typically useful info for others.
