### ISSUE TITLE
how can this happen?

### ISSUE THREAD

**Issue by cheenpo** [githubteacher/intermediate-may#25]
$git pull
Already up-to-date.

$git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

```
modified:   Cary.md
```

no changes added to commit (use "git add" and/or "git commit -a")

**Comment by githubstudent** [comment]
@cheenpo Ah, there's nothing wrong here. You have modified `Cary.md`, but never committed those changes. Does that make sense?

**Comment by cheenpo** [comment]
:+1:
